/**
 * tina/auth.ts — Auth.js (next-auth v4) options: Google OAuth, one account
 * per editor.
 *
 * Authentication (who is this?)  -> Google, via Auth.js
 * Authorization (may they edit?) -> the `editors` allowlist collection
 *                                   (content/editors/index.json), matched on
 *                                   the Google account email (`uidProp`).
 *
 * Mount point: Tina's admin SPA hard-codes its Auth.js SessionProvider to
 * basePath "/api/tina/auth" (tinacms 3.13), and the Tina backend serves
 * Auth.js there through its built-in `auth` extra route. So:
 *   - Google redirect URI  = https://<host>/api/tina/auth/callback/google
 *   - NEXTAUTH_URL         = https://<host>/api/tina/auth   (path REQUIRED —
 *     next-auth derives its basePath from it)
 * There is deliberately no separate api/auth/[...nextauth] function.
 */
import { TinaAuthJSOptions } from "tinacms-authjs";
import * as GoogleModule from "next-auth/providers/google";
import type { AuthOptions } from "next-auth";
// "next-auth/providers" (no trailing segment) isn't in the package's
// exports map, only the "./providers/*" glob — so the subpath needs an
// explicit "index".
import type { Provider } from "next-auth/providers/index";
// Generated by `tinacms build` / `tinacms dev` (gitignored).
import databaseClient from "./__generated__/databaseClient.js";

// next-auth v4 has no package.json "type" field (plain CJS). Under
// Vercel's Node16/NodeNext type-check of api/ functions, TS treats every
// .d.ts in a CJS-format package as CJS too, regardless of it using ESM
// `export default` syntax — so a default import, a default type-only
// import, and even `(typeof mod)["default"]` all still resolve to the
// whole module-namespace type, not the callable default. (Confirmed by
// trying all three; every one produces the identical "has no call
// signatures" error.) This is a known incompatibility between next-auth
// v4's declarations and strict Node16/NodeNext consumers, not something
// fixable from this side of the import. `any` on the factory call is the
// narrowest honest workaround: only this one call is untyped, and casting
// its result back to `Provider` keeps `providers: Provider[]` below
// meaningfully checked.
const GoogleProviderFactory: any = (GoogleModule as any).default ?? (GoogleModule as any);

const base = TinaAuthJSOptions({
  databaseClient,
  secret: process.env.NEXTAUTH_SECRET!,
  // Google's stable per-user handle we can put in a plain-text allowlist.
  uidProp: "email",
  providers: [
    GoogleProviderFactory({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }) as Provider,
  ],
  debug: process.env.TINA_AUTH_DEBUG === "true",
});

export const authOptions: AuthOptions = {
  ...base,
  // The editor's role ("user" vs "guest") is baked into the JWT at sign-in and
  // NOT re-checked afterwards, so removing someone from the allowlist does not
  // end a session that already exists. A short lifetime bounds that window
  // (next-auth's default is 30 days). Emergency revoke: rotate NEXTAUTH_SECRET.
  session: { strategy: "jwt", maxAge: 8 * 60 * 60 },
  callbacks: {
    ...base.callbacks,
    // Refuse Google accounts whose email is not verified.
    signIn: async ({ account, profile }) => {
      if (account?.provider !== "google") return false;
      return (profile as { email_verified?: boolean } | undefined)?.email_verified === true;
    },
    // The allowlist compares exact strings; normalise case before Tina's
    // own jwt callback does the lookup.
    jwt: async (params) => {
      if (typeof params.token.email === "string") {
        params.token.email = params.token.email.toLowerCase();
      }
      return base.callbacks!.jwt!(params);
    },
  },
};
