/**
 * tina/auth.ts — Auth.js (next-auth v4) options: Google OAuth, one account
 * per editor.
 *
 * Authentication (who is this?)  -> Google, via Auth.js
 * Authorization (may they edit?) -> the `editors` allowlist collection
 *                                   (content/editors/index.json), matched on
 *                                   the Google account email (`uidProp`).
 *
 * Mount point: Tina's admin SPA hard-codes its Auth.js SessionProvider to
 * basePath "/api/tina/auth" (tinacms 3.13), and the Tina backend serves
 * Auth.js there through its built-in `auth` extra route. So:
 *   - Google redirect URI  = https://<host>/api/tina/auth/callback/google
 *   - NEXTAUTH_URL         = https://<host>/api/tina/auth   (path REQUIRED —
 *     next-auth derives its basePath from it)
 * There is deliberately no separate api/auth/[...nextauth] function.
 */
import { TinaAuthJSOptions } from "tinacms-authjs";
import { createRequire } from "node:module";
import type { AuthOptions } from "next-auth";
// "next-auth/providers" (no trailing segment) isn't in the package's
// exports map, only the "./providers/*" glob — so the subpath needs an
// explicit "index".
import type { Provider } from "next-auth/providers/index";
// Generated by `tinacms build` / `tinacms dev` (gitignored).
import databaseClient from "./__generated__/databaseClient.js";

// next-auth v4's Google provider is Babel-style CJS: `exports.default =
// Google; exports.__esModule = true;`. Real Node ESM's CJS interop (NOT
// TypeScript's `esModuleInterop`, which is a compile-time approximation of
// it — this is a genuine runtime behaviour difference) binds an ESM
// `default` import to the *whole* `module.exports` object verbatim, even
// when that object already has its own `.default` property — it does not
// collapse the two. So `import Google from "next-auth/providers/google"`
// under real Node ESM yields `{ default: Google }`, not `Google`, and
// calling it throws "is not a function" (confirmed empirically: a plain
// CJS `require()` of the same module correctly gives `{ default: Google }`
// with `.default` unwrapping to the function in ONE step — it's
// specifically the ESM import path that adds an extra layer).
// `createRequire` sidesteps the ESM loader's interop entirely and gets the
// same shape `require()` always has, which needs only the ordinary single
// `.default` unwrap.
const require = createRequire(import.meta.url);
const GoogleProviderFactory: (options: { clientId: string; clientSecret: string }) => Provider =
  require("next-auth/providers/google").default;

const base = TinaAuthJSOptions({
  databaseClient,
  secret: process.env.NEXTAUTH_SECRET!,
  // Google's stable per-user handle we can put in a plain-text allowlist.
  uidProp: "email",
  providers: [
    GoogleProviderFactory({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
  ],
  debug: process.env.TINA_AUTH_DEBUG === "true",
});

export const authOptions: AuthOptions = {
  ...base,
  // The editor's role ("user" vs "guest") is baked into the JWT at sign-in and
  // NOT re-checked afterwards, so removing someone from the allowlist does not
  // end a session that already exists. A short lifetime bounds that window
  // (next-auth's default is 30 days). Emergency revoke: rotate NEXTAUTH_SECRET.
  session: { strategy: "jwt", maxAge: 8 * 60 * 60 },
  callbacks: {
    ...base.callbacks,
    // Refuse Google accounts whose email is not verified.
    signIn: async ({ account, profile }) => {
      if (account?.provider !== "google") return false;
      return (profile as { email_verified?: boolean } | undefined)?.email_verified === true;
    },
    // The allowlist compares exact strings; normalise case before Tina's
    // own jwt callback does the lookup.
    jwt: async (params) => {
      if (typeof params.token.email === "string") {
        params.token.email = params.token.email.toLowerCase();
      }
      return base.callbacks!.jwt!(params);
    },
  },
};
